### PR TITLE
Create svg-open-sign snippet

### PR DESCRIPTION
**Pull request by chrisroselli**
SVG Open Sign solution.

### CODE REVIEW

**Comment by johnsiwicki** [comment]
Chris should we get that SVG in core?

**Comment by chrisroselli** [comment]
Ya, I'll setup a file.

**Comment by johnsiwicki** [comment]
@chrisroselli , I love what the svg with the php. Check out what we do on the new templates open signs http://www.tarheelbasementsystems.com/

**Comment by chrisroselli** [comment]
Ya, noticed that. That's probably a simpler solution. Just was hot and heavy on deploying some SVG, ha.

**Comment by chrisroselli** [comment]
I'll close the PR then, since we'll probably stick with the new template style you mentioned.

**Pull request closed without merging**
